title: Dominion Ezekwesiri Egwuekwe
logo: mypic.jpg
description: Data analyst with 2 years of experience a results-driven and thorough professional with expertise in understanding and evaluating complex datasets to produce useful insights. Competent in using programs like SQL,Excel and Power BI from statistical analysis, data visualisation, and predictive modelling.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
