title: Dominion Egwuekwe
logo: My Profile Pics.jpg
description: Data analyst with 5 years of experience in interpreting and evaluating complex datasets to generate actionable insights and communicate results in a clear, accessible manner.
Proficient in SQL and Excel for data extraction, transformation, and manipulation; skilled in Power BI for visualization; and experienced in Python for programming and advanced analysis.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
