title: Dominion Ezekwesiri Egwuekwe
logo: mypic.jpg
description: Data analyst with 2 years of experience an expertise in understanding and evaluating complex datasets to produce useful insights. Competent in using programs like SQL,Excel and Power BI.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
